version: '3'

services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - TZ=Asia/Shanghai
      - REDIS_CONN_STRING=redis://redis:6379
      # - REDIS_PASSWORD=your_password
      # - REDIS_MASTER_NAME=your_master_name

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai

volumes:
  redis-data: