version: '3'

services:
  neo-api:
    build: .
    container_name: neo-api
    ports:
      - "3000:3000"  # API 服务端口
      - "6379:6379"  # Redis 端口
    env_file:
      - .env        # 使用 .env 文件中的环境变量
    volumes:
      - data:/data  # 数据持久化
    restart: always # 自动重启

volumes:
  data:
    driver: local 