[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"

[[services]]
name = "new-api"
internal_port = 3000
envs = { TZ = "Asia/Shanghai" }
depends_on = { redis = "healthy" }

[[services]]
name = "redis"
dockerfile = "Dockerfile.redis"
internal_port = 6379
envs = { TZ = "Asia/Shanghai" }
health_check = { interval = "10s", timeout = "5s", retries = 5, path = "/", grace_period = "30s" } 